### ISSUE TITLE
SQL Server connection string adds vigehcxkyh56m 

### ISSUE THREAD

**Issue by JudedeDude** [OctopusDeploy/azure-marketplace#2]
For some reason the connection string has added vigehcxkyh56m to the end of the sql server name. So it looks like sqlservervigehcxkyh56m .database.windows.net instead of sqlserver.database.windows.net
I checked my template and no mention of vigehcxkyh56m and I looked in the override in VSTS and nothing there
I also looked into the ps1 script and nothing there of vigehcxkyh56m to append to name
I also looked into the portal, looked at the connection string and vigehcxkyh56m  is not shown.
Is there any reason why vigehcxkyh56m will be added to the SQL server name for the connectionstring?

This of course fails the installation due to the correct string not being used

**Comment by MJRichardson** [comment]
When the template creates the `sqlServerName` it [appends a unique string](https://github.com/OctopusDeploy/azure-marketplace/blob/master/mainTemplate.json#L174).

That explains the `vigehcxkyh56m`.  So the question would seem to be why it isn't working for you.

Could you explain exactly how you are using the template?

**Comment by JudedeDude** [comment]
that has fixed my issue, I made the line look like this "sqlServerName": "[concat(parameters('sqlServerName'))]"
